name: Run All Required Tests for rAuth0
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - v**.**.**

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      branch-name: ${{ steps.vars.outputs.short_ref }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v1.2.0
      with:
        fetch-depth: 1
        # The branch that triggered the workflow.
        ref: ${{ github.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Artifactory Login
      shell: bash
      run: |
        docker login "${{ secrets.DOCKER_REGISTRY }}" -u "${{ secrets.ARTIFACTORY_USER }}" -p "${{ secrets.ARTIFACTORY_KEY }}"

    - name: Set Variables
      id: vars
      run: |
        echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

  build-environments:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Build the rAuth0 Docker Environment
      shell: bash
      run: |
        docker build -t ${{ secrets.DOCKER_REGISTRY }}/docker/rauth0 .

  docker-push:
    runs-on: ubuntu-latest
    needs: [setup, build-environments]
    steps:
    - name: Tag Docker Images with Branch
      shell: bash
      run: |
        docker tag ${{ secrets.DOCKER_REGISTRY }}/docker/rauth0:latest ${{ secrets.DOCKER_REGISTRY }}/docker/rauth0:${{ needs.setup.outputs.branch-name }}
    - name: Push Docker Images to Artifactory
      shell: bash
      env:
        DOCKER_REGISTRY: ${( secrets.DOCKER_REGISTRY }}
      run: |
        docker push ${{ secrets.DOCKER_REGISTRY }}/docker/rauth0:${{ needs.setup.outputs.branch-name }}