name: Run All Required Tests for Vortex
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - v**.**.**

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      branch-name: ${{ steps.vars.outputs.short_ref }}
    steps:
    # Because we are using a self-hosted runner we need to clean the directories
    # from previous jobs that may have been completed.
    - name: Clean Workspace
      run: |
        sudo rm -rf ${GITHUB_WORKSPACE}

    - name: Checkout code
      uses: actions/checkout@v1.2.0
      with:
        fetch-depth: 1
        # The branch that triggered the workflow.
        ref: ${{ github.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Artifactory Login
      shell: bash
      env:
        ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
        ARTIFACTORY_KEY: ${{ secrets.ARTIFACTORY_KEY }}
        DOCKER_REGISTRY: ${( secrets.DOCKER_REGISTRY }}
      run: |
        docker login "$DOCKER_REGISTRY" -u "$ARTIFACTORY_USER" -p "$ARTIFACTORY_KEY"

    - name: Set Variables
      id: vars
      run: |
        echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

  build-environments:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Build the rAuth0 Docker Environment
      shell: bash
      env:
        DOCKER_REGISTRY: ${( secrets.DOCKER_REGISTRY }}
      run: |
        docker build -t ${DOCKER_REGISTRY}/docker/rauth0 .

  docker-push:
    runs-on: ubuntu-latest
    needs: [setup, build-environments]
    steps:
    - name: Tag Docker Images with Branch
      shell: bash
      env:
        DOCKER_REGISTRY: ${( secrets.DOCKER_REGISTRY }}
      run: |
        docker tag ${DOCKER_REGISTRY}/docker/rauth0:latest ${DOCKER_REGISTRY}/docker/rauth0:${{ needs.setup.outputs.branch-name }}
    - name: Push Docker Images to Artifactory
      shell: bash
      env:
        DOCKER_REGISTRY: ${( secrets.DOCKER_REGISTRY }}
      run: |
        docker push ${DOCKER_REGISTRY}/docker/rauth0:${{ needs.setup.outputs.branch-name }}